######################################################################
# Automatically generated by qmake (2.01a) Thu Dec 17 18:14:24 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += GlSplat.h GlSplat_config.h Shader.h
SOURCES += demo.cpp GlSplat.cpp Shader.cpp
RESOURCES += glsplat.qrc
